# Generated by Django 6.0.2 on 2026-03-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nts_app', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
