# Generated by Django 6.0.3 on 2026-03-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nts_app', '0004_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
